---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - scikit-learn=1.5.2
  - pandas=2.2.2
  - xgboost=2.1.1
